id: P94B6BE96
initial_creation_type: input
source_metadata:
  Title: Pārājikā (Texts from Nepal)
  Editor: '-'
  Publisher: Savitri Prakashan
  Place of Publication: Pune, India
  Year: '2013'
  Maṃjuśrīpārājikā:
    Text Version: Romanized
    Input Personnel: Anjana Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:09:00.788814'
last_modified_at: '2022-03-08T17:09:00.788823'
